/*
 * Default layout component for app/.
 * ------------------------------------------------------------------------------
 *
 */

import type { Metadata } from 'next';
import { GTFAdieu, GTFAdieu_Slanted, GTFAdieu_Backslant, Source_Sans_3 } from './fonts';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html
			lang="en"
			className={`
      ${GTFAdieu.variable}
      ${GTFAdieu_Slanted.variable}
      ${GTFAdieu_Backslant.variable}
      ${Source_Sans_3.variable}
    `}
		>
			<body>{children}</body>
		</html>
	);
}
